# other
aspect.ratio: element_number

# basic
# basic-line
line: element_line
# basic-rect
rect: element_rect
# basic-text
text: element_text
# basic-title
title: element_text

# axis
# axis-title
axis.title: element_text
axis.title.x: element_text
axis.title.x.top: element_text
axis.title.x.bottom: element_text
axis.title.y: element_text
axis.title.y.left: element_text
axis.title.y.right: element_text
# axis-text
axis.text: element_text
axis.text.x: element_text
axis.text.x.top: element_text
axis.text.x.bottom: element_text
axis.text.y: element_text
axis.text.y.left: element_text
axis.text.y.right: element_text
# axis-ticksstyle
axis.ticks: element_line
axis.ticks.x: element_line
axis.ticks.x.top: element_line
axis.ticks.x.bottom: element_line
axis.ticks.y: element_line
axis.ticks.y.left: element_line
axis.ticks.y.right: element_line
# axis-tickslength
axis.ticks.length: element_unit
axis.ticks.length.x: element_unit
axis.ticks.length.x.top: element_unit
axis.ticks.length.x.bottom: element_unit
axis.ticks.length.y: element_unit
axis.ticks.length.y.left: element_unit
axis.ticks.length.y.right: element_unit
# axis-line
axis.line: element_line
axis.line.x: element_line
axis.line.x.top: element_line
axis.line.x.bottom: element_line
axis.line.y: element_line
axis.line.y.left: element_line
axis.line.y.right: element_line
# legned
# legend-spacing
legend.spacing: element_unit
legend.spacing.x: element_unit
legend.spacing.y: element_unit
# legend-key
legend.key: element_rect
legend.key.size: element_unit
legend.key.height: element_unit
legend.key.width: element_unit
# legend-box
legend.box: element_direction
legend.box.just: element_just
legend.box.margin: element_margin
legend.box.background: element_rect
legend.box.spacing: element_unit
# legend-text
legend.text: element_text
legend.text.align: element_align
# lengend-title
legend.title: element_text
legend.title.align: element_align
# legeng-overall
legend.background: element_rect
legend.margin: element_margin
legend.position: element_position
legend.direction: element_direction
legend.justification: element_justification
# panel 
# panel-spacing
panel.spacing: element_unit
panel.spacing.x: element_unit
panel.spacing.y: element_unit
# panel-grid
panel.grid: element_line
panel.grid.major: element_line
panel.grid.major.x: element_line
panel.grid.major.y: element_line
panel.grid.minor: element_line
panel.grid.minor.x: element_line
panel.grid.minor.y: element_line
# panel-others
panel.background: element_rect
panel.border: element_rect
panel.ontop: element_logical

# plot
# plot-title
plot.title: element_text
plot.subtitle: element_text
plot.title.position: element_title_position
# plot-caption
plot.caption: element_text
plot.caption.position: element_title_position
# plot-tag
plot.tag: element_text
plot.tag.position: element_tag_position
# plot-others
plot.margin: element_margin
plot.background: element_rect

# strip
# strip-background
strip.background: element_rect
strip.background.x: element_rect
strip.background.y: element_rect
# strip-text
strip.text: element_text
strip.text.x: element_text
strip.text.y: element_text
strip.text.y.left: element_text
# strip-others
strip.placement: element_placement
strip.switch.pad.grid: element_unit
strip.switch.pad.wrap: element_unit

